### ISSUE TITLE
SELECT queries returning more than one record (i.e.: lists) should not raise an error if no records are returned

### ISSUE THREAD

**Issue by prryplatypus** [ahopkins/mayim#11]
A select statement for an empty table raises a `mayim.exception.RecordNotFound` exception, whereas in cases in which a list should be returned, it feels more "correct" behaviour if it would simply return an empty list.

```py
## ./executor.py
class UserExecutor(PostgresExecutor):
    async def select_all_users(self) -> List[User]:
        ...
```

```sql
-- ./queries/select_all_users.sql
SELECT id, username FROM public.users;
```

### Traceback
```
Traceback (most recent call last):
  File "handle_request", line 83, in handle_request
    FutureStatic,
  File "C:\Users\Usuario\Desktop\sanic-forum\sanic_forum\blueprints\api\v1\users\blueprint.py", line 17, in ping_human
    users = await executor.select_all_users()
  File "c:\Users\Usuario\Desktop\sanic-forum\.venv\lib\site-packages\mayim\executor\sql.py", line 229, in decorated_function
    results = await self._execute(
  File "c:\Users\Usuario\Desktop\sanic-forum\.venv\lib\site-packages\mayim\executor\sql.py", line 67, in _execute
    raise RecordNotFound("not found")
mayim.exception.RecordNotFound: not found
```

**Comment by ahopkins** [comment]
Agreed, `RecordNotFound` should only be raised when searching for a single item.
